kind: pipeline
type: docker
name: default

steps:
- name: docker-build-publish
  image: plugins/docker
  settings:
    username: 
      from_secret: DOCKERHUB_USERNAME
    password: 
      from_secret: DOCKERHUB_PASSWORD
    repo: aloknicole/app
    tags: latest
    when:
      branch: main